language: python
python:
  - "2.7"
# command to install dependencies
install:
  # Install pip dependencies
  - "pip install -r requirements.txt"
  # start flask server
  #- start_server.sh
before_script:
  - ls $TRAVIS_BUILD_DIR
# command to run tests
script: nosetests