language: python
python:
  - "2.7"
# command to install dependencies
install:
  # Install pip dependencies
  - "pip install -r requirements.txt"
before_script:
  - ls $TRAVIS_BUILD_DIR
  # change to build directory
  - cd $TRAVIS_BUILD_DIR
  # start flask server
  - sh start_server.sh
# command to run tests
script: nosetests